- name: Generate UUID
  delegate_to: localhost
  run_once: true
  set_fact:
    # reference cluster_id the same as other variables
    cluster_id: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
