- name: Add Current Play Hosts to /etc/hosts
  blockinfile:
      path: /etc/hosts
      block: |
        {% for item in ansible_play_batch %}
        {{ hostvars[item].ansible_host }}   {{ hostvars[item].hostname }}    
        {% endfor %}
        {% for item in ansible_play_batch %}
        {{ hostvars[item].ansible_host }}   {{ hostvars[item].basename }}    
        {% endfor %}
