# extract tarball "elastic-agent-99.999.9-linux-x86_64.tar.gz" to /tmp/elastic-agent/
- name: Extract Tarball
  unarchive:
    remote_src: yes
    src: "/tmp/{{ filename }}"
    dest: "/tmp/{{ staging_dir }}"
    owner: "{{ user }}"
    group: "{{ user_password }}"
    mode: 0750
    extra_opts:
    - --strip
    - 1
