# manual section spacing added for readability
# variables moved to demonstrate adding them at the group level

all:

  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:

    ungrouped:
      hosts:
        127.7.8.9:
        127.9.8.7:

    databases:
      vars:
        database_example_var: true
      children:
        east_databases:
          hosts:
            eastdb:
              ansible_host: 127.3.3.3
              basename: eastdb
              hostname: eastdb.local
        west_databases:
          hosts:
            westdb:
              ansible_host: 127.4.4.4
              basename: westdb
              hostname: westdb.local

    webservers:
      vars:
        web_example_var: true
      children:
        east_webservers:
          hosts:
            eastweb:
              ansible_host: 127.2.2.2
              basename: eastweb
              hostname: eastweb.local
        west_webservers:
          hosts:
            westweb:
              ansible_host: 127.1.1.1
              basename: westweb
              hostname: westweb.local
